import { SIZE_TYPES } from '../settings';

const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],

  screenType: SIZE_TYPES.DESKTOP,

  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      category: 'bed',
      price: 30,
      oldPrice: 100,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
      favorite: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 3,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 1,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      customStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2017/06/29/07/32/chair-2453307_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2019/03/23/14/14/chair-4075443__340.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-30',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 24',
      category: 'chair',
      image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
      price: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-40',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-41',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-42',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-43',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-44',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-45',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-46',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-47',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-48',
      name: 'Aenean Ru Bristique 23',
      category: 'sofa',
      image:
        'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-49',
      name: 'Aenean Ru Bristique 24',
      category: 'dining',
      image:
        'https://cdn.pixabay.com/photo/2016/11/18/14/05/brick-wall-1834784__340.jpg',
      price: 30,
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-50',
      name: 'Aenean Ru Bristique 24',
      category: 'dining',
      image:
        'https://cdn.pixabay.com/photo/2016/11/18/14/05/brick-wall-1834784__340.jpg',
      price: 30,
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-51',
      name: 'Aenean Ru Bristique 24',
      category: 'dining',
      image:
        'https://cdn.pixabay.com/photo/2016/11/18/14/05/brick-wall-1834784__340.jpg',
      price: 30,
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-52',
      name: 'Aenean Ru Bristique 24',
      category: 'dining',
      image:
        'https://cdn.pixabay.com/photo/2016/11/18/14/05/brick-wall-1834784__340.jpg',
      price: 30,
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-53',
      name: 'Aenean Ru Bristique 24',
      category: 'dining',
      image:
        'https://cdn.pixabay.com/photo/2016/11/18/14/05/brick-wall-1834784__340.jpg',
      price: 30,
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-54',
      name: 'Aenean Ru Bristique 24',
      category: 'table',
      image: 'https://cdn.pixabay.com/photo/2017/03/28/12/10/chairs-2181947__340.jpg',
      price: 30,
      newFurniture: true,
    },
  ],
  cart: {
    products: {},
  },
  brands: [
    {
      id: 'brand1',
      name: 'Brand 1',
      logo: './images/1logo.png',
    },
    {
      id: 'brand2',
      name: 'Brand 2',
      logo: './images/2logo.png',
    },
    {
      id: 'brand3',
      name: 'Brand 3',
      logo: './images/3logo.png',
    },
    {
      id: 'brand4',
      name: 'Brand 4',
      logo: './images/4logo.png',
    },
    {
      id: 'brand5',
      name: 'Brand 5',
      logo: './images/5logo.png',
    },
    {
      id: 'brand6',
      name: 'Brand 6',
      logo: './images/6logo.png',
    },
  ],

  promoted: [
    {
      img: 'https://cdn.pixabay.com/photo/2018/10/28/12/37/bedroom-3778695__340.jpg',
      name: 'Indoor furniture',
      h1: 'INDOOR FURNITURE',
      h2: 'save up to 50% of all furniture',
    },
    {
      img: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940168__340.jpg',
      name: 'Guest room chairs',
      h1: 'GUEST ROOM CHAIRS',
      h2: 'save up to 50% of all furniture',
    },
    {
      img: 'https://cdn.pixabay.com/photo/2018/10/28/12/37/bedroom-3778695__340.jpg',
      name: 'Bedroom collection',
      h1: 'BEDROOM collection',
      h2: '$200 off',
    },
  ],

  promotion: {
    leftImage:
      'https://media.istockphoto.com/photos/interior-with-armchair-and-coffee-table-3d-rendering-picture-id1158575634?k=6&m=1158575634&s=612x612&w=0&h=Fkh9dLz9W8TKkKwJstagndsCu92badT0y6m-w8iqB-g=',
    leftDescription: ['Guest room', 'Sofa', '-20%'],
    rightUpImage:
      'https://cdn.pixabay.com/photo/2017/08/03/15/38/architecture-2576906_1280.jpg',
    rightUpDescription: ['Office', 'chair', 'Collection', '$200.00'],
    rightDownImage:
      'https://media.istockphoto.com/photos/interior-of-modern-living-room-with-white-fabric-sofa-over-blue-wall-picture-id1136363292?k=6&m=1136363292&s=612x612&w=0&h=4DjPA8KlSLP6l75B7Bh0zZXbmTjjYLS5KThkvDn86Rs=',
    rightDownDescription: ['Special', 'collection', 'Save up', '45%', 'of furniture'],
  },

  prodPopup: {
    isShown: false,
    productId: 'aenean-ru-bristique-23',
  },
  feedbacks: [
    {
      id: 'feedback1',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip',
      foto:
        'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      name: 'John Doe',
      description: 'Furniture client',
    },
    {
      id: 'feedback2',
      text:
        'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta',
      foto:
        'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      name: 'John Smith',
      description: 'New bed owner',
    },
    {
      id: 'feedback3',
      text:
        'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident',
      foto:
        'https://images.pexels.com/photos/1933873/pexels-photo-1933873.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      name: 'Kristoff Koloski',
      description: 'Kitchen designer',
    },
  ],

  blogPosts: [
    {
      id: 'post1',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.',
      foto: '',
      author: 'John Doe',
      title: 'Products That Fight Static',
      date: '15 JAN 2016',
      comments: '4',
      image:
        'https://images.pexels.com/photos/1676037/pexels-photo-1676037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'post2',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.',
      foto: '',
      author: 'John Smith',
      title: 'Products That Fight Static',
      date: '15 JAN 2016',
      comments: '4',
      image:
        'https://images.pexels.com/photos/1676037/pexels-photo-1676037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'post3',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.',
      foto: '',
      author: 'Kristoff Koloski',
      title: 'Products That Fight Static',
      date: '15 JAN 2016',
      comments: '4',
      image:
        'https://images.pexels.com/photos/1676037/pexels-photo-1676037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
  ],

  gallery: {
    topSeller: [
      {
        id: 'gallery1',
        name: 'Aenean Ru Bristique 28',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869078270?k=6&m=869078270&s=612x612&w=0&h=vlZiqejf8mg7V_t9K1K6UU5820560QqETmIRXVTcfI4=',
        oldPrice: 300,
        price: 150,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery2',
        name: 'Aenean Ru Bristique 24',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869080484?k=6&m=869080484&s=612x612&w=0&h=5Ioq7-GOIX0yPVQMXtiTMMlNZ3roO4OtSzc7N-I4sic=',
        oldPrice: 500,
        price: 250,
        stars: 2,
        active: true,
      },
      {
        id: 'gallery3',
        name: 'Aenean Ru Bristique 29',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869078170?k=6&m=869078170&s=612x612&w=0&h=huq8AkURZgYUidgi84oMbov7_PWy2vMkaYCkpQBP2DU=',
        oldPrice: 600,
        price: 300,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery4',
        name: 'Aenean Ru Bristique 54',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869080512?k=6&m=869080512&s=612x612&w=0&h=Hx8HpJBMERcs06Itp_BdXTUI4RHLGfq2lqWquiFjWFY=',
        oldPrice: 400,
        price: 200,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery5',
        name: 'Aenean Ru Bristique 37',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869079246?k=6&m=869079246&s=612x612&w=0&h=5lzGcMbpPjDf1yQsey0CSG6D6JwefrodvjWiBwFnpHM=',
        oldPrice: 350,
        price: 175,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery6',
        name: 'Aenean Ru Bristique 77',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869080588?k=6&m=869080588&s=612x612&w=0&h=KdsgZ-yabtmnthVoyZnTHs2RiPWCEiF3UhTPrby1uz4=',
        oldPrice: 550,
        price: 275,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery7',
        name: 'Aenean Ru Bristique 63',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869078270?k=6&m=869078270&s=612x612&w=0&h=vlZiqejf8mg7V_t9K1K6UU5820560QqETmIRXVTcfI4=',
        oldPrice: 300,
        price: 150,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery8',
        name: 'Aenean Ru Bristique 223',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869080484?k=6&m=869080484&s=612x612&w=0&h=5Ioq7-GOIX0yPVQMXtiTMMlNZ3roO4OtSzc7N-I4sic=',
        oldPrice: 500,
        price: 250,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery9',
        name: 'Aenean Ru Bristique 294',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869078170?k=6&m=869078170&s=612x612&w=0&h=huq8AkURZgYUidgi84oMbov7_PWy2vMkaYCkpQBP2DU=',
        oldPrice: 600,
        price: 300,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery10',
        name: 'Aenean Ru Bristique 524',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869080512?k=6&m=869080512&s=612x612&w=0&h=Hx8HpJBMERcs06Itp_BdXTUI4RHLGfq2lqWquiFjWFY=',
        oldPrice: 400,
        price: 200,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery11',
        name: 'Aenean Ru Bristique 327',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869079246?k=6&m=869079246&s=612x612&w=0&h=5lzGcMbpPjDf1yQsey0CSG6D6JwefrodvjWiBwFnpHM=',
        oldPrice: 350,
        price: 175,
        stars: 2,
        active: false,
      },
      {
        id: 'gallery12',
        name: 'Aenean Ru Bristique 277',
        image:
          'https://media.istockphoto.com/photos/armchair-isolated-on-white-background-3d-rendering-picture-id869080588?k=6&m=869080588&s=612x612&w=0&h=KdsgZ-yabtmnthVoyZnTHs2RiPWCEiF3UhTPrby1uz4=',
        oldPrice: 550,
        price: 275,
        stars: 2,
        active: false,
      },
    ],
    featured: [
      {
        id: 'aenean-ru-bristique-1',
        name: 'Aenean Ru Bristique 1',
        category: 'bed',
        price: 30,
        oldPrice: 100,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
        favorite: true,
        compare: false,
        active: true,
      },
      {
        id: 'aenean-ru-bristique-2',
        name: 'Aenean Ru Bristique 2',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 3,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-3',
        name: 'Aenean Ru Bristique 3',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 1,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
        favorite: true,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-4',
        name: 'Aenean Ru Bristique 4',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-5',
        name: 'Aenean Ru Bristique 5',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-6',
        name: 'Aenean Ru Bristique 6',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-7',
        name: 'Aenean Ru Bristique 7',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-8',
        name: 'Aenean Ru Bristique 8',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-9',
        name: 'Aenean Ru Bristique 9',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-10',
        name: 'Aenean Ru Bristique 10',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-11',
        name: 'Aenean Ru Bristique 11',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-12',
        name: 'Aenean Ru Bristique 12',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
    ],
    saleOff: [
      {
        id: 'aenean-ru-bristique-13',
        name: 'Aenean Ru Bristique 13',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-14',
        name: 'Aenean Ru Bristique 14',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-15',
        name: 'Aenean Ru Bristique 15',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-16',
        name: 'Aenean Ru Bristique 16',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
        favorite: false,
        compare: false,
        active: true,
      },
      {
        id: 'aenean-ru-bristique-17',
        name: 'Aenean Ru Bristique 17',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-18',
        name: 'Aenean Ru Bristique 18',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-19',
        name: 'Aenean Ru Bristique 19',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-20',
        name: 'Aenean Ru Bristique 20',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-21',
        name: 'Aenean Ru Bristique 21',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-22',
        name: 'Aenean Ru Bristique 22',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-23',
        name: 'Aenean Ru Bristique 23',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image:
          'https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-24',
        name: 'Aenean Ru Bristique 24',
        category: 'bed',
        price: 30,
        stars: 2,
        customStars: 0,
        promo: 'sale',
        newFurniture: true,
        image: 'https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_1280.jpg',
        favorite: false,
        compare: false,
        active: false,
      },
    ],
    topRated: [
      {
        id: 'aenean-ru-bristique-25',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-26',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2017/06/29/07/32/chair-2453307_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-27',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: true,
      },
      {
        id: 'aenean-ru-bristique-28',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2019/03/23/14/14/chair-4075443__340.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-29',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-30',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-31',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-32',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-33',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-34',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-35',
        name: 'Aenean Ru Bristique 24',
        category: 'chair',
        image: 'https://cdn.pixabay.com/photo/2015/04/20/13/13/chair-731171_1280.jpg',
        price: 45,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
      {
        id: 'aenean-ru-bristique-36',
        name: 'Aenean Ru Bristique 23',
        category: 'sofa',
        image:
          'https://media.istockphoto.com/photos/modern-grey-sofa-picture-id1186974930?b=1&k=6&m=1186974930&s=170667a&w=0&h=VwN3RmuVYxsBaKBTFYFIKeyQ3UoqJJYddImhIHnhxW8=',
        price: 30,
        stars: 2,
        promo: 'sale',
        newFurniture: true,
        active: false,
      },
    ],
  },
};

export default initialState;
